### DISCUSSION TITLE
How to deal with "Error uploading files"?

### DISCUSSION THREAD

**Discussion by PencilVoid** [bcomnes/deploy-to-neocities#108] [Q&A] [answered]
I'd like to preface this by stating I am not very smart and this is my first time using Github Actions. When I push a commit, everything seems to go fine except for "Deploy to neocities". In the log, there is an error stating "Error uploading files". The log contains two more lines after this:
```
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy to neocities
```
and then ends. There is also a warning about Node.js 12 actions being deprecated, but I'm not sure whether that is related.
I have no idea how to fix this, and would appreciate assistance from anyone who's encountered this and managed to get around it. For reference, my `.github/workflows/neocities.yml` file looks like this:
```
name: Deploy to neocities

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: site

```
The contents of the website are contained in a folder named `site`.
