### DISCUSSION TITLE
Excluding certain directory?

### DISCUSSION THREAD

**Discussion by brillcheese** [bcomnes/deploy-to-neocities#125] [Q&A]
im quite new to git actions. i was wondering if there was a way to exclude certain files/directories?

i only have this so far. doesnt work either
```
on:
  push:
    branches:
      - main
    paths-ignore: 
     - 'path/to/folder/**'
```
