### DISCUSSION TITLE
Wrong path on deploy

### DISCUSSION THREAD

**Discussion by HWTjac0** [bcomnes/deploy-to-neocities#148] [General]
My workflow file looks like this
```
name: Deploy to neocities
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1.1.13
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public
```

And I get this error
`ENOENT: no such file or directory, stat '/home/runner/work/neocities-website/neocities-website/public'`
In root of repository I just have public directory where I put all of my contents. It's simple static website with no build steps and "neocities-website" is the name of the repository. What might be the problem? I am using actions first time.

**Comment by bcomnes** [comment]
You still need to have a checkout step


```
name: Deploy to neocities
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1.1.13
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public
```
