### DISCUSSION TITLE
Trying to get started, encountered this issue: "npm ERR! code EN0ENT"

### DISCUSSION THREAD

**Discussion by JamesGauvreau** [bcomnes/deploy-to-neocities#150] [Q&A] [answered]
This is my first time running a Github action. 

The first three stages went fine, but in "Install deps and build," I get the error sequence that I've posted below. I'm pretty sure that the problem is on my side, since nobody else is talking about this, but I'd like to confirm before I start to tear things apart.  (edited: messed up the formatting originally)

```
Run npm i
  npm i
  npm run build
  shell: /usr/bin/bash -e {0}
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/neocity/neocity/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/neocity/neocity/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-06-24T01_45_54_385Z-debug-0.log
Error: Process completed with exit code 254.
```

**Comment by bcomnes** [comment]
`ENOENT: no such file or directory, open '/home/runner/work/neocity/neocity/package.json'`

Sounds like you are trying to run an `npm install` on a proejct that doesn't have a `package.json`. If you aren't using `npm` you don't need to run that step. If you have more details about the repo you are trying to build, I can provide more specific advice.

**Comment by JamesGauvreau** [comment]
Thank you! That's helped me make a bit more progress. 

I'm currently trying to upload a pair of .html files contained in the repo ```/neocity/public```, and I'm getting the following error message: 

```
Error: ENOENT: no such file or directory, stat '/home/runner/work/neocity/neocity/public'
```

I don't see anything in the code which would produce that address, especially the doubled "neocity/neocity." I don't think that I've organized the repo incorrectly, at least on Github (on my computer, the directory is called _neocities_ rather than _neocity_, but I don't see how that would affect anything).

Right now, ```jobs``` reads as follows: 
```
jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to neocities
    uses: bcomnes/deploy-to-neocities@v1
    with:
        api_token: $secrets.NEOCITIES_API_TOKEN
        cleanup: false
        dist_dir: public
```

**Comment by bcomnes** [comment]
Looks like your action isn't checking out the source code of your project, so its not present when the neocities action tries to deploy it. Add the checkout step to your action like this:

```yml
jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to neocities
    uses: bcomnes/deploy-to-neocities@v1
    with:
        api_token: $secrets.NEOCITIES_API_TOKEN
        cleanup: false
        dist_dir: public
```

Hope that helps! Let me know how it goes.

**Reply by JamesGauvreau** [reply]
Thanks again! I'm making progress but I'm not all of the way through yet. 

I've included the error message below. I've seen some people say that this kind of error might indicate a problem with the token, but I'm pretty certain that I've got the correct API Key. I even pasted it directly into the code just to rule out the possibility that I was using secrets incorrectly. 

I don't seen anything in the current edition of the tool which would indicate that the tool is trying to find nonexistent javascript files, so I'm pretty sure that JSON is referring to the javascript that exists in bcomnes/deploy-to-neocities, but maybe I'm wrong about that. 

**Error log**
```
Run bcomnes/deploy-to-neocities@v1
Starting inspecting stage...
JSONHTTPError: Forbidden
    at handleResponse (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:2211:40)
    at processTicksAndRejections (node:internal/process/task_queues:9[6](https://github.com/JamesGauvreau/neocity/actions/runs/5384035204/jobs/9771487593#step:3:7):5)
    at async Promise.all (index 1)
    at async NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:20559:43)
    at async doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:21653:1[7](https://github.com/JamesGauvreau/neocity/actions/runs/5384035204/jobs/9771487593#step:3:8))
Error: Forbidden
```

**Current code**
```
name: Deploy to Neocities

# only run on changes to master
on:
  push:
    branches:
      - master

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: $************
        cleanup: false
        dist_dir: public
```
