### DISCUSSION TITLE
Running into "Actions/checkout@v3" error

### DISCUSSION THREAD

**Discussion by JamesGauvreau** [bcomnes/deploy-to-neocities#195] [Q&A]
I've been banging my head against this one for a while. I know that Deploy-to-neocities has been updated to run on node20, and I _thought_ that I've updated my code appropriately, but I must be doing something wrong. 

I'm including the code from my deploy.yml file; please let me know if I've made an error with this file or if I need to look elsewhere for the problem. 

Thanks in advance. 

```
name: Deploy to Neocities

# only run on changes to master
on:
  push:
    branches:
      - master

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v2
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public
        protected_files: 'images/writing/*/*'
```
