### DISCUSSION TITLE
Working workflow YAML updates/suggestion

### DISCUSSION THREAD

**Discussion by awetos** [bcomnes/deploy-to-neocities#215] [General]
Thank you for making this program!

Update suggestion: 
I got it working by removing npm and Node.js
rename api_key to api_token
reorder api_token, dist_dir, cleanup, protected_files
change name to public/
rename master to main

Remember to add your actual API key to your repository > settings > security > secrets and variables
Add the yaml file in your repository > Actions > "new workflow file" (or add it in the .github/workflows folder)

Also if anyone knows, I'm not sure if it was safe for me to remove node.js and npm, but it seems to still work without it. 

working edition:
```
name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  node_version: lts/*

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        dist_dir: public/
        cleanup: true
        protected_files: 'dropbox/*'
        neocities_supporter: false # set this to true if you have a supporter account and want to bypass unsuported files filter.
        preview_before_deploy: true
```
original:
```
name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - master

env:
  FORCE_COLOR: 1
  node_version: lts/*

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # If you have a different build process, replace this with your own build steps
    - name: Install deps and build
      run: |
        npm i
        npm run build
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        neocities_supporter: false # set this to true if you have a supporter account and want to bypass unsuported files filter.
        preview_before_deploy: true # print a deployment plan prior to waiting for files to upload.
        dist_dir: public`
```
