### DISCUSSION TITLE
How do I use this action?

### DISCUSSION THREAD

**Discussion by Woolton** [bcomnes/deploy-to-neocities#60] [Q&A] [answered]
This is my first time using actions and I just can't figure it out, as much as I update my [repo](github.com/woolton/woolneocities), no change is reflected on my neocities site. How do I know if the action is even triggering?

**Comment by bcomnes** [comment]
Hey @Woolton sorry I can't seem to see that link, is your woolneocities repo private?

Basically, in any repo on GitHub, you create a folder in your default branch (master or main depending on your setting) with this path:

```
.github/workflows/
````

(so, the `.github` folder (including the period in front) with a `workflows` folder inside of it)

Then create an action yml file, it can be called whatever you want. The following link is an example action called `neocities.yml`:

https://github.com/bcomnes/mine.css/blob/14d62951198fe6542b857f13e1456665cdf8f590/.github/workflows/neocities.yml#L1-L27

Then you need to set a GitHub action secret in your repository settings called `secrets.NEOCITIES_API_TOKEN` from your Neocities API token that you generate on their website.

Then the action will work whenever you push to your default branch! You can see previous runs of this example here: https://github.com/bcomnes/mine.css/actions

Read through that action and it mostly self describes:

- Runs on any push to the master branch (you may need to rename this if you use main)
- Runs in ubuntu
- Checks out the code
- Installs Node.js (you can install any other tool you want though, like ruby or python)
- Installs the Node.js npm deps
- Runs a script to build the website, this might be different for your site.
- Then finally, deploys to neocities, from the default deploy folder (named `public`).

If you make that repo public, I can maybe see what the issue is.

**Comment by plainoldcheese** [comment]
I'm having an issue as well. (I assume similar). The github action runs but when it gets to the deploying to neocities part it seems to be skipping that (see image below). I have the API key set as a action secret and can't figure out why it's not updating. 

![image](https://github.com/bcomnes/deploy-to-neocities/assets/41850179/d8fd0cab-c5d4-4da6-ac99-b2452d502f74)

I've made my repo public: https://github.com/plainoldcheese/plainoldcheese.neocities.org
this is my yml file

```yml
name: 🐈 Deploy to neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 🖥️Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        if: ${{ env.NEOCITIES_API_TOKEN }}
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public
```
