### ISSUE TITLE
"Unable to find Node version 'lts/*"

### ISSUE THREAD

**Issue by pdmcharms** [bcomnes/deploy-to-neocities#114]
Hi, I hope you can help me again. I've done more research and decided to build the site with 11ty. Whenever I try to deploy, I get this error that seems to be from the workflows/main.yml file that I copy and pasted from here (with the changes only to the dist_dir).
`
> Run actions/setup-node@v1
  with:
    node-version: lts/*
    always-auth: false
Error: Unable to find Node version 'lts/*' for platform linux and architecture x64. 
`

**Comment by bcomnes** [comment]
I looked at your action, and it looks like you had used the v1 versions of `actions/checkout` and `actions/setup-node`, probably because thats what the (old) example here had listed. I've updated the example here, and you should do the same in your actions file. e.g. use the v3 of these actions. You can enable automatic updates (in the form of PRs) by adding a dependably file to your .github folder if you wish. Here is an example: https://github.com/bcomnes/deploy-to-neocities/blob/master/.github/dependabot.yml

```yml
    steps:
    - uses: actions/checkout@v3
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
```
