### ISSUE TITLE
Uploading issues, even though that the YAML is valid

### ISSUE THREAD

**Issue by lime360** [bcomnes/deploy-to-neocities#178]
here is the issue:
```sh
Error: ENOENT: no such file or directory, stat '/home/runner/work/awesome-neocities/awesome-neocities/public'
Error: ENOENT: no such file or directory, stat '/home/runner/work/awesome-neocities/awesome-neocities/public'
```

the yaml:
```yaml
name: Deploy to Neocities

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: ./public
```
