### ISSUE TITLE
odd ENOENT error...

### ISSUE THREAD

**Issue by riflesniper** [bcomnes/deploy-to-neocities#212]
i'm running into a snag with the repository for one of my sites. i tried taking a look at one of the other ENOENT issue that was on here, but the fixes provided in that thread did not help. here's the error log,

```
Current runner version: '2.322.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'bcomnes/deploy-to-neocities@v3' (SHA:60adbf96af7b57e13a551e35ff57b74142f9655f)
Complete job name: deploy

Run actions/checkout@v4
Syncing repository: riflesniper/neocities-stuff
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/18118e0f-a429-4a04-afb1-5a63097f22ca' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/neocities-stuff/neocities-stuff
Deleting the contents of '/home/runner/work/neocities-stuff/neocities-stuff'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
/usr/bin/git log -1 --format=%H
88aa4eaeb8c6d7ad2d02dfdeb43635daa45eda5e

Run bcomnes/deploy-to-neocities@v3
  with:
    api_key: ***
    cleanup: false
    neocities_supporter: true
    dist_dir: dist_dir
    preview_before_deploy: true
Unexpected error/throw during deployment:


Error: ENOENT: no such file or directory, stat '/home/runner/work/neocities-stuff/neocities-stuff/dist_dir'
    at async Object.stat (node:internal/fs/promises:1032:18)
    at async run (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v3/dist/index.cjs:51814:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/runner/work/neocities-stuff/neocities-stuff/dist_dir'
}
Error: ENOENT: no such file or directory, stat '/home/runner/work/neocities-stuff/neocities-stuff/dist_dir'

Post job cleanup.
/usr/bin/git version
git version 2.48.1
Temporarily overriding HOME='/home/runner/work/_temp/f506c6e1-c532-4bfe-b10f-a70bae614833' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/neocities-stuff/neocities-stuff
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"

Cleaning up orphan processes
```

and here is my YML file.

```
name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        neocities_supporter: true # set this to true if you have a supporter account and want to bypass unsuported files filter.
        dist_dir: dist_dir
```

i am completely clueless when it comes to code stuff like this, it worked perfectly fine with my other site repository, i'm not really sure what's happening here. even when i deleted and reinitialized this repository, the error persisted.
