### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Obspogon** [bcomnes/deploy-to-neocities#62]
I get an error when I try using this.
Here's the logs:
[logs_86.zip](https://github.com/bcomnes/deploy-to-neocities/files/7622195/logs_86.zip)
I use a modified version from the example YML:

```
name: Deploy to neocities

# only run on changes to master
on:
    push:
        branches:
[logs_86.zip](https://github.com/bcomnes/deploy-to-neocities/files/7622195/logs_86.zip)

            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to neocities
              uses: bcomnes/deploy-to-neocities@v1
              with:
                  api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
                  cleanup: false
                  dist_dir: .

```

**Comment by bcomnes** [comment]
Do you have a link to the repo you are trying to deploy?

**Comment by bcomnes** [comment]
Quick fix, try putting your website inside of a folder and set your `dist_dir` directly.  I think it's failing trying to deploy the root folder which contains all of the git junk.

**Comment by Obspogon** [comment]
I've sent an invitation to my repository. Also, now the action works with no errors, but doesn't actually upload to neocities. Here's the new log:
[logs_89.zip](https://github.com/bcomnes/deploy-to-neocities/files/7628889/logs_89.zip)

**Comment by bcomnes** [comment]
You need to check out your code in an action to interact with it, so add that step and the contents of your site will then be present in the working directory to deploy.

But you should put the contents of your website into a folder inside of the repo, such as `website` or `public` because otherwise if you try to deploy `/` it will also deploy all of your hidden files like `.git` and `.github` which may cause neocities to unhappy. 

```
name: Deploy to neocities

# only run on changes to master
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.4.0
            - name: Deploy to neocities
              uses: bcomnes/deploy-to-neocities@v1
              with:
                  api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
                  cleanup: false
                  dist_dir: /
```
