### ISSUE TITLE
Error: must pass apiKey as first argument

### ISSUE THREAD

**Issue by Nioobers** [bcomnes/deploy-to-neocities#79]
When I try to deploy, I have this error : 
```
Run bcomnes/deploy-to-neocities@master
  with:
    cleanup: false
    dist_dir: /
AssertionError: must pass apiKey as first argument
    at new NeocitiesAPIClient (/home/runner/work/_actions/bcomnes/deploy-to-neocities/master/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:70:1)
    at doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/master/webpack:/deploy-to-neocities/index.js:22:1)
Error: must pass apiKey as first argument
```
The yaml : 
```yaml
name: Deploy to neociteis

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Use Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 12
    - run: npm i
    - run: npm build
    - run: npm run

    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@master
      with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: /

```
